name: LoveOTC

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: preview

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
          run_install: false

      - name: Get pnpm store
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build React
        run: pnpm install && pnpm build

      - name: Move wwwroot
        run: mv dist TSystems.LoveOTC/wwwroot

      - name: Build
        run: |
          dotnet publish TSystems.LoveOTC/TSystems.LoveOTC.csproj -c Release -o LoveOTC -r linux-x64 --self-contained true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./LoveOTC
          publish_branch: Infra
